[tasks.run]
alias = "scan"

[tasks.scan]
command = "cargo"
args = ["run", "--", "--timeout", "5"]

[tasks.build-wasm]
command = "wasm-pack"
args = ["build", "--target", "web", "--", "--no-default-features", "--features", "wasm"]